language: android
android:
  components:
    - tools
    - build-tools-27.0.3
    - android-28
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

sudo: required

jdk:
  - oraclejdk8

install: true

script:
  - chmod +x ./gradlew
