language: android
android:
  components:
    - tools
    - build-tools-27.0.3
    - android-28
    - platform-tools
  licenses:
    - '.+'

sudo: required

jdk:
  - oraclejdk8

install: true

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease --stacktrace
